[package]
name = "bevy_ios_iap_egui"
version = "0.2.0"
edition = "2021"

[dependencies]
bevy_ios_iap = "0.6.0"
bevy = { version = "0.15", default-features = false }
bevy_egui = { version = "0.32", default-features = false }
egui_extras = { version = "0.30" }
