[package]
name = "bevy_ios_iap_egui"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ios_iap = "0.5"
bevy = { version = "0.15", default-features = false }
bevy_egui = { version = "0.31", default-features = false }
egui_extras = { version = "0.29" }
