// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct IosIapStorefront IosIapStorefront;
void __swift_bridge__$IosIapStorefront$_free(void* self);

void* __swift_bridge__$Vec_IosIapStorefront$new(void);
void __swift_bridge__$Vec_IosIapStorefront$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapStorefront$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapStorefront$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapStorefront$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapStorefront$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapStorefront$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapStorefront$as_ptr(void* vec_ptr);

typedef struct IosIapEnvironment IosIapEnvironment;
void __swift_bridge__$IosIapEnvironment$_free(void* self);

void* __swift_bridge__$Vec_IosIapEnvironment$new(void);
void __swift_bridge__$Vec_IosIapEnvironment$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapEnvironment$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapEnvironment$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapEnvironment$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapEnvironment$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapEnvironment$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapEnvironment$as_ptr(void* vec_ptr);

typedef struct IosIapTransactionReason IosIapTransactionReason;
void __swift_bridge__$IosIapTransactionReason$_free(void* self);

void* __swift_bridge__$Vec_IosIapTransactionReason$new(void);
void __swift_bridge__$Vec_IosIapTransactionReason$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapTransactionReason$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapTransactionReason$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapTransactionReason$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapTransactionReason$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapTransactionReason$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapTransactionReason$as_ptr(void* vec_ptr);

typedef struct IosIapTransaction IosIapTransaction;
void __swift_bridge__$IosIapTransaction$_free(void* self);

void* __swift_bridge__$Vec_IosIapTransaction$new(void);
void __swift_bridge__$Vec_IosIapTransaction$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapTransaction$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapTransaction$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapTransaction$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapTransaction$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapTransaction$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapTransaction$as_ptr(void* vec_ptr);

typedef struct IosIapPurchaseResult IosIapPurchaseResult;
void __swift_bridge__$IosIapPurchaseResult$_free(void* self);

void* __swift_bridge__$Vec_IosIapPurchaseResult$new(void);
void __swift_bridge__$Vec_IosIapPurchaseResult$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapPurchaseResult$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapPurchaseResult$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapPurchaseResult$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapPurchaseResult$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapPurchaseResult$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapPurchaseResult$as_ptr(void* vec_ptr);

typedef struct IosIapProductType IosIapProductType;
void __swift_bridge__$IosIapProductType$_free(void* self);

void* __swift_bridge__$Vec_IosIapProductType$new(void);
void __swift_bridge__$Vec_IosIapProductType$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapProductType$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapProductType$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapProductType$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapProductType$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapProductType$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapProductType$as_ptr(void* vec_ptr);

typedef struct IosIapProduct IosIapProduct;
void __swift_bridge__$IosIapProduct$_free(void* self);

void* __swift_bridge__$Vec_IosIapProduct$new(void);
void __swift_bridge__$Vec_IosIapProduct$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapProduct$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapProduct$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapProduct$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapProduct$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapProduct$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapProduct$as_ptr(void* vec_ptr);

void* __swift_bridge__$IosIapProduct$new(void* id, void* display_price, void* display_name, void* description, double price, void* product_type);
void* __swift_bridge__$IosIapProductType$new_consumable(bool non);
void* __swift_bridge__$IosIapProductType$new_non_renewable(void);
void* __swift_bridge__$IosIapProductType$new_auto_renewable(void);
void* __swift_bridge__$IosIapPurchaseResult$success(void);
void* __swift_bridge__$IosIapPurchaseResult$canceled(void);
void* __swift_bridge__$IosIapPurchaseResult$pending(void);
void* __swift_bridge__$IosIapEnvironment$sandbox(void);
void* __swift_bridge__$IosIapEnvironment$production(void);
void* __swift_bridge__$IosIapEnvironment$xcode(void);
void* __swift_bridge__$IosIapStorefront$storefront(void* id, void* country_code);
void* __swift_bridge__$IosIapTransaction$new_transaction(uint64_t id, void* product_id, void* app_bundle_id, uint64_t purchase_date, int32_t purchased_quantity, void* storefront_country_code, uint64_t signed_date, bool is_upgraded, void* product_type, void* reason, void* environment, void* storefront);
void __swift_bridge__$IosIapTransaction$add_revocation(void* t, uint64_t date);
void __swift_bridge__$IosIapTransaction$add_expiration(void* t, uint64_t date);
void* __swift_bridge__$IosIapTransactionReason$renewal(void);
void* __swift_bridge__$IosIapTransactionReason$purchase(void);
void __swift_bridge__$products_received(void* products);
void __swift_bridge__$purchase_processed(void* result);
void __swift_bridge__$transaction_update(void* t);


