// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct IosIapTransactionFinishResponse IosIapTransactionFinishResponse;
void __swift_bridge__$IosIapTransactionFinishResponse$_free(void* self);

void* __swift_bridge__$Vec_IosIapTransactionFinishResponse$new(void);
void __swift_bridge__$Vec_IosIapTransactionFinishResponse$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapTransactionFinishResponse$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapTransactionFinishResponse$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapTransactionFinishResponse$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapTransactionFinishResponse$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapTransactionFinishResponse$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapTransactionFinishResponse$as_ptr(void* vec_ptr);

typedef struct IosIapTransactionResponse IosIapTransactionResponse;
void __swift_bridge__$IosIapTransactionResponse$_free(void* self);

void* __swift_bridge__$Vec_IosIapTransactionResponse$new(void);
void __swift_bridge__$Vec_IosIapTransactionResponse$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapTransactionResponse$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapTransactionResponse$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapTransactionResponse$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapTransactionResponse$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapTransactionResponse$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapTransactionResponse$as_ptr(void* vec_ptr);

typedef struct IosIapProductsResponse IosIapProductsResponse;
void __swift_bridge__$IosIapProductsResponse$_free(void* self);

void* __swift_bridge__$Vec_IosIapProductsResponse$new(void);
void __swift_bridge__$Vec_IosIapProductsResponse$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapProductsResponse$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapProductsResponse$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapProductsResponse$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapProductsResponse$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapProductsResponse$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapProductsResponse$as_ptr(void* vec_ptr);

typedef struct IosIapRevocationReason IosIapRevocationReason;
void __swift_bridge__$IosIapRevocationReason$_free(void* self);

void* __swift_bridge__$Vec_IosIapRevocationReason$new(void);
void __swift_bridge__$Vec_IosIapRevocationReason$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapRevocationReason$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapRevocationReason$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapRevocationReason$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapRevocationReason$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapRevocationReason$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapRevocationReason$as_ptr(void* vec_ptr);

typedef struct IosIapCurrency IosIapCurrency;
void __swift_bridge__$IosIapCurrency$_free(void* self);

void* __swift_bridge__$Vec_IosIapCurrency$new(void);
void __swift_bridge__$Vec_IosIapCurrency$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapCurrency$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapCurrency$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapCurrency$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapCurrency$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapCurrency$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapCurrency$as_ptr(void* vec_ptr);

typedef struct IosIapSubscriptionRenewalState IosIapSubscriptionRenewalState;
void __swift_bridge__$IosIapSubscriptionRenewalState$_free(void* self);

void* __swift_bridge__$Vec_IosIapSubscriptionRenewalState$new(void);
void __swift_bridge__$Vec_IosIapSubscriptionRenewalState$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapSubscriptionRenewalState$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapSubscriptionRenewalState$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapSubscriptionRenewalState$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapSubscriptionRenewalState$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapSubscriptionRenewalState$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapSubscriptionRenewalState$as_ptr(void* vec_ptr);

typedef struct IosIapSubscriptionStatus IosIapSubscriptionStatus;
void __swift_bridge__$IosIapSubscriptionStatus$_free(void* self);

void* __swift_bridge__$Vec_IosIapSubscriptionStatus$new(void);
void __swift_bridge__$Vec_IosIapSubscriptionStatus$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapSubscriptionStatus$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapSubscriptionStatus$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapSubscriptionStatus$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapSubscriptionStatus$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapSubscriptionStatus$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapSubscriptionStatus$as_ptr(void* vec_ptr);

typedef struct IosIapSubscriptionPeriodUnit IosIapSubscriptionPeriodUnit;
void __swift_bridge__$IosIapSubscriptionPeriodUnit$_free(void* self);

void* __swift_bridge__$Vec_IosIapSubscriptionPeriodUnit$new(void);
void __swift_bridge__$Vec_IosIapSubscriptionPeriodUnit$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapSubscriptionPeriodUnit$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapSubscriptionPeriodUnit$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapSubscriptionPeriodUnit$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapSubscriptionPeriodUnit$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapSubscriptionPeriodUnit$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapSubscriptionPeriodUnit$as_ptr(void* vec_ptr);

typedef struct IosIapSubscriptionPeriod IosIapSubscriptionPeriod;
void __swift_bridge__$IosIapSubscriptionPeriod$_free(void* self);

void* __swift_bridge__$Vec_IosIapSubscriptionPeriod$new(void);
void __swift_bridge__$Vec_IosIapSubscriptionPeriod$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapSubscriptionPeriod$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapSubscriptionPeriod$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapSubscriptionPeriod$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapSubscriptionPeriod$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapSubscriptionPeriod$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapSubscriptionPeriod$as_ptr(void* vec_ptr);

typedef struct IosIapSubscriptionInfo IosIapSubscriptionInfo;
void __swift_bridge__$IosIapSubscriptionInfo$_free(void* self);

void* __swift_bridge__$Vec_IosIapSubscriptionInfo$new(void);
void __swift_bridge__$Vec_IosIapSubscriptionInfo$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapSubscriptionInfo$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapSubscriptionInfo$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapSubscriptionInfo$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapSubscriptionInfo$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapSubscriptionInfo$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapSubscriptionInfo$as_ptr(void* vec_ptr);

typedef struct IosIapStorefront IosIapStorefront;
void __swift_bridge__$IosIapStorefront$_free(void* self);

void* __swift_bridge__$Vec_IosIapStorefront$new(void);
void __swift_bridge__$Vec_IosIapStorefront$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapStorefront$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapStorefront$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapStorefront$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapStorefront$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapStorefront$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapStorefront$as_ptr(void* vec_ptr);

typedef struct IosIapEnvironment IosIapEnvironment;
void __swift_bridge__$IosIapEnvironment$_free(void* self);

void* __swift_bridge__$Vec_IosIapEnvironment$new(void);
void __swift_bridge__$Vec_IosIapEnvironment$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapEnvironment$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapEnvironment$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapEnvironment$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapEnvironment$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapEnvironment$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapEnvironment$as_ptr(void* vec_ptr);

typedef struct IosIapTransactionReason IosIapTransactionReason;
void __swift_bridge__$IosIapTransactionReason$_free(void* self);

void* __swift_bridge__$Vec_IosIapTransactionReason$new(void);
void __swift_bridge__$Vec_IosIapTransactionReason$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapTransactionReason$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapTransactionReason$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapTransactionReason$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapTransactionReason$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapTransactionReason$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapTransactionReason$as_ptr(void* vec_ptr);

typedef struct IosIapTransaction IosIapTransaction;
void __swift_bridge__$IosIapTransaction$_free(void* self);

void* __swift_bridge__$Vec_IosIapTransaction$new(void);
void __swift_bridge__$Vec_IosIapTransaction$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapTransaction$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapTransaction$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapTransaction$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapTransaction$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapTransaction$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapTransaction$as_ptr(void* vec_ptr);

typedef struct IosIapStoreKitError IosIapStoreKitError;
void __swift_bridge__$IosIapStoreKitError$_free(void* self);

void* __swift_bridge__$Vec_IosIapStoreKitError$new(void);
void __swift_bridge__$Vec_IosIapStoreKitError$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapStoreKitError$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapStoreKitError$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapStoreKitError$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapStoreKitError$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapStoreKitError$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapStoreKitError$as_ptr(void* vec_ptr);

typedef struct IosIapPurchaseError IosIapPurchaseError;
void __swift_bridge__$IosIapPurchaseError$_free(void* self);

void* __swift_bridge__$Vec_IosIapPurchaseError$new(void);
void __swift_bridge__$Vec_IosIapPurchaseError$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapPurchaseError$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapPurchaseError$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapPurchaseError$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapPurchaseError$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapPurchaseError$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapPurchaseError$as_ptr(void* vec_ptr);

typedef struct IosIapPurchaseResponse IosIapPurchaseResponse;
void __swift_bridge__$IosIapPurchaseResponse$_free(void* self);

void* __swift_bridge__$Vec_IosIapPurchaseResponse$new(void);
void __swift_bridge__$Vec_IosIapPurchaseResponse$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapPurchaseResponse$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapPurchaseResponse$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapPurchaseResponse$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapPurchaseResponse$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapPurchaseResponse$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapPurchaseResponse$as_ptr(void* vec_ptr);

typedef struct IosIapProductType IosIapProductType;
void __swift_bridge__$IosIapProductType$_free(void* self);

void* __swift_bridge__$Vec_IosIapProductType$new(void);
void __swift_bridge__$Vec_IosIapProductType$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapProductType$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapProductType$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapProductType$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapProductType$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapProductType$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapProductType$as_ptr(void* vec_ptr);

typedef struct IosIapProduct IosIapProduct;
void __swift_bridge__$IosIapProduct$_free(void* self);

void* __swift_bridge__$Vec_IosIapProduct$new(void);
void __swift_bridge__$Vec_IosIapProduct$drop(void* vec_ptr);
void __swift_bridge__$Vec_IosIapProduct$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_IosIapProduct$pop(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapProduct$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_IosIapProduct$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_IosIapProduct$len(void* vec_ptr);
void* __swift_bridge__$Vec_IosIapProduct$as_ptr(void* vec_ptr);

void* __swift_bridge__$IosIapProduct$new(void* id, void* display_price, void* display_name, void* description, double price, void* product_type);
void __swift_bridge__$IosIapProduct$subscription(void* t, void* info);
void* __swift_bridge__$IosIapProductType$new_consumable(bool non);
void* __swift_bridge__$IosIapProductType$new_non_renewable(void);
void* __swift_bridge__$IosIapProductType$new_auto_renewable(void);
void* __swift_bridge__$IosIapPurchaseResponse$success(void* t);
void* __swift_bridge__$IosIapPurchaseResponse$canceled(void* id);
void* __swift_bridge__$IosIapPurchaseResponse$pending(void* id);
void* __swift_bridge__$IosIapPurchaseResponse$unknown(void* id);
void* __swift_bridge__$IosIapPurchaseResponse$error(void* e);
void* __swift_bridge__$IosIapPurchaseResponse$purchase_error(void* error, void* localized_description);
void* __swift_bridge__$IosIapPurchaseResponse$storekit_error(void* error, void* localized_description);
void* __swift_bridge__$IosIapPurchaseError$invalid_quantity(void);
void* __swift_bridge__$IosIapPurchaseError$product_unavailable(void);
void* __swift_bridge__$IosIapPurchaseError$purchase_not_allowed(void);
void* __swift_bridge__$IosIapPurchaseError$ineligible_for_offer(void);
void* __swift_bridge__$IosIapPurchaseError$invalid_offer_identifier(void);
void* __swift_bridge__$IosIapPurchaseError$invalid_offer_price(void);
void* __swift_bridge__$IosIapPurchaseError$invalid_offer_signature(void);
void* __swift_bridge__$IosIapPurchaseError$missing_offer_parameters(void);
void* __swift_bridge__$IosIapStoreKitError$unknown(void);
void* __swift_bridge__$IosIapStoreKitError$user_cancelled(void);
void* __swift_bridge__$IosIapStoreKitError$network_error(void* e);
void* __swift_bridge__$IosIapStoreKitError$system_error(void* e);
void* __swift_bridge__$IosIapStoreKitError$not_available_in_storefront(void);
void* __swift_bridge__$IosIapStoreKitError$not_entitled(void);
void* __swift_bridge__$IosIapEnvironment$sandbox(void);
void* __swift_bridge__$IosIapEnvironment$production(void);
void* __swift_bridge__$IosIapEnvironment$xcode(void);
void* __swift_bridge__$IosIapStorefront$storefront(void* id, void* country_code);
void* __swift_bridge__$IosIapTransaction$new_transaction(uint64_t id, void* product_id, void* app_bundle_id, uint64_t purchase_date, uint64_t original_purchase_date, int32_t purchased_quantity, void* storefront_country_code, uint64_t signed_date, bool is_upgraded, uint64_t original_id, void* json_representation, void* product_type, void* reason, void* environment, void* storefront);
void __swift_bridge__$IosIapTransaction$add_revocation(void* t, uint64_t date);
void __swift_bridge__$IosIapTransaction$add_expiration(void* t, uint64_t date);
void __swift_bridge__$IosIapTransaction$add_currency(void* t, void* currency);
void __swift_bridge__$IosIapTransaction$add_currency_code(void* t, void* code);
void __swift_bridge__$IosIapTransaction$revocation_reason(void* t, void* reason);
void __swift_bridge__$IosIapTransaction$web_order_line_item_id(void* t, void* id);
void __swift_bridge__$IosIapTransaction$subscription_group_id(void* t, void* id);
void __swift_bridge__$IosIapTransaction$app_account_token(void* t, void* uuid);
void* __swift_bridge__$IosIapTransactionReason$renewal(void);
void* __swift_bridge__$IosIapTransactionReason$purchase(void);
void* __swift_bridge__$IosIapTransactionFinishResponse$finished(void* t);
void* __swift_bridge__$IosIapTransactionFinishResponse$error(void* e);
void* __swift_bridge__$IosIapTransactionFinishResponse$unknown(uint64_t id);
void* __swift_bridge__$IosIapSubscriptionInfo$new(void* group_id, void* period, bool is_eligible_for_intro_offer, void* state);
void* __swift_bridge__$IosIapSubscriptionPeriod$new(void* unit, int32_t value);
void* __swift_bridge__$IosIapSubscriptionPeriodUnit$day(void);
void* __swift_bridge__$IosIapSubscriptionPeriodUnit$week(void);
void* __swift_bridge__$IosIapSubscriptionPeriodUnit$month(void);
void* __swift_bridge__$IosIapSubscriptionPeriodUnit$year(void);
void* __swift_bridge__$IosIapSubscriptionRenewalState$subscribed(void);
void* __swift_bridge__$IosIapSubscriptionRenewalState$expired(void);
void* __swift_bridge__$IosIapSubscriptionRenewalState$in_billing_retry_period(void);
void* __swift_bridge__$IosIapSubscriptionRenewalState$in_grace_period(void);
void* __swift_bridge__$IosIapSubscriptionRenewalState$revoked(void);
void* __swift_bridge__$IosIapSubscriptionStatus$new(void* state, void* transaction);
void* __swift_bridge__$IosIapCurrency$new(void* identifier, bool is_iso_currency);
void* __swift_bridge__$IosIapRevocationReason$developer_issue(void);
void* __swift_bridge__$IosIapRevocationReason$other(void);
void* __swift_bridge__$IosIapProductsResponse$done(void* items);
void* __swift_bridge__$IosIapProductsResponse$error(void* error);
void* __swift_bridge__$IosIapTransactionResponse$done(void* items);
void* __swift_bridge__$IosIapTransactionResponse$error(void* error);
void __swift_bridge__$products_received(int64_t request, void* response);
void __swift_bridge__$all_transactions(int64_t request, void* response);
void __swift_bridge__$current_entitlements(int64_t request, void* response);
void __swift_bridge__$purchase_processed(int64_t request, void* result);
void __swift_bridge__$transaction_update(void* t);
void __swift_bridge__$transaction_finished(int64_t request, void* t);


