name: CD-rust

on:
  push:
    tags:
     - 'rs-*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      contents: write
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    - name: Add iOS targets
      run: rustup target add aarch64-apple-ios aarch64-apple-ios-sim x86_64-apple-ios

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: "./bevy_ios_iap"

    - name: make xcframework archive
      run: make zip

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: ${{ contains(github.ref, 'rc') }}
        files: |
          ./RustXcframework.xcframework.zip
          ./RustXcframework.xcframework.sha256.txt